# Initial reference: Engine/Source/Programs/Horde/Horde.Server/docker-compose.yml
# https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Programs/Horde/Horde.Server/docker-compose.yml

# NOTE: Mounted volumes under "./volume" for easy viewing, modifying, and learning purposes (not ideal for a production environment)

include:
  - docker-compose.network.yml

services:
  mongodb:
    image: mongo:7.0.5-jammy
    restart: always
    environment:
      # Default username and password, change these!
      MONGO_INITDB_ROOT_USERNAME: horde
      MONGO_INITDB_ROOT_PASSWORD: dbPass123
    command: --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 30002:30002
    command: redis-server --save 60 1 --port 30002 --loglevel warning
    volumes:
      - redis:/data

  horde-server:
    # Requires access to Unreal Engine's image repository on GitHub
    image: ghcr.io/epicgames/horde-server:latest
    restart: always
    environment:
      # Horde uses standard configuration from ASP.NET, allowing values to be set through env vars and files.
      # See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/
      # To configure via config file, see the mounted directory and file ./volume/horde-server/data/server.json.
      # The env vars below are set as they're configured through Docker Compose
      Horde__HttpPort: 13340
      Horde__Http2Port: 13342
      Horde__RedisConnectionConfig: redis:30002
      Horde__DatabaseConnectionString: mongodb://horde:dbPass123@mongodb:27017/Horde?authSource=admin
    ports:
      - 13340:13340 # HTTP/1
      - 13342:13342 # HTTP/2
    volumes:
      - ./volume/horde-server/data:/app/Data

# Provide persistence between container restarts for MongoDB and Redis
volumes:
  mongodb:
    driver: local
  redis:
    driver: local
