include:
  - ../docker-compose.network.yml

services:
  portainer:
    image: portainer/portainer-ce:2.20.3
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - 9000:9000
      - 9443:9443

volumes:
  portainer:
    name: portainer
    driver: local
